//! Path Traversal and File Inclusion Rules

use crate::rules::{AttackType, Confidence, Rule, RuleBuilder, Severity};
use anyhow::Result;

pub fn rules(paranoia_level: u8) -> Result<Vec<Rule>> {
    let all_rules = vec![
        // Basic path traversal
        RuleBuilder::new(930100, "Path Traversal: Basic ../ sequence")
            .description("Detects basic directory traversal")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"\.\.(/|\\)")
            .base_score(8)
            .cwe(22)
            .owasp("A01:2021-Broken Access Control")
            .tags(&["traversal", "lfi"])
            .build()?,
        RuleBuilder::new(930101, "Path Traversal: URL encoded ..%2f")
            .description("Detects URL-encoded path traversal")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(\.\.%2f|%2e%2e%2f|%2e%2e/|\.%2e/|%2e\./)")
            .base_score(9)
            .cwe(22)
            .tags(&["traversal", "lfi", "encoded"])
            .build()?,
        RuleBuilder::new(930102, "Path Traversal: Double URL encoded")
            .description("Detects double URL-encoded path traversal")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(%252e%252e|%252f|%255c)")
            .base_score(9)
            .cwe(22)
            .tags(&["traversal", "lfi", "encoded"])
            .build()?,
        RuleBuilder::new(930103, "Path Traversal: UTF-8 encoded")
            .description("Detects UTF-8 encoded path traversal")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(%c0%ae|%c1%9c|%c0%af)")
            .base_score(9)
            .cwe(22)
            .tags(&["traversal", "lfi", "encoded"])
            .build()?,
        RuleBuilder::new(930104, "Path Traversal: Backslash variant")
            .description("Detects backslash path traversal (Windows)")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"\.\.\\")
            .base_score(8)
            .cwe(22)
            .tags(&["traversal", "lfi", "windows"])
            .build()?,
        // OS file access
        RuleBuilder::new(930110, "Path Traversal: /etc/passwd access")
            .description("Detects Linux password file access")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)/etc/(passwd|shadow|group|hosts)")
            .base_score(10)
            .cwe(22)
            .tags(&["traversal", "lfi", "unix"])
            .build()?,
        RuleBuilder::new(930111, "Path Traversal: /proc access")
            .description("Detects Linux proc filesystem access")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)/proc/(self|[0-9]+)/(environ|cmdline|fd|maps)")
            .base_score(9)
            .cwe(22)
            .tags(&["traversal", "lfi", "unix"])
            .build()?,
        RuleBuilder::new(930112, "Path Traversal: Windows system files")
            .description("Detects Windows system file access")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(c:\\windows|c:\\winnt|c:\\boot\.ini|c:\\system32)")
            .base_score(10)
            .cwe(22)
            .tags(&["traversal", "lfi", "windows"])
            .build()?,
        RuleBuilder::new(930113, "Path Traversal: Config file access")
            .description("Detects common config file access")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(\.htaccess|\.htpasswd|\.env|wp-config\.php|config\.php)")
            .base_score(9)
            .cwe(22)
            .tags(&["traversal", "lfi", "config"])
            .build()?,
        // Local File Inclusion
        RuleBuilder::new(930120, "LFI: PHP wrapper php://")
            .description("Detects PHP stream wrapper")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)php://(input|filter|data)")
            .base_score(10)
            .cwe(98)
            .tags(&["lfi", "rfi", "php"])
            .build()?,
        RuleBuilder::new(930121, "LFI: PHP expect wrapper")
            .description("Detects PHP expect:// for command execution")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)expect://")
            .base_score(10)
            .cwe(98)
            .tags(&["lfi", "rfi", "php", "rce"])
            .build()?,
        RuleBuilder::new(930122, "LFI: file:// protocol")
            .description("Detects file:// protocol usage")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)file://")
            .base_score(8)
            .cwe(22)
            .tags(&["lfi", "file-protocol"])
            .build()?,
        RuleBuilder::new(930123, "LFI: Null byte injection")
            .description("Detects null byte for extension bypass")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(%00|\\x00|\x00)")
            .base_score(9)
            .cwe(626)
            .tags(&["lfi", "null-byte"])
            .build()?,
        // Remote File Inclusion
        RuleBuilder::new(930130, "RFI: HTTP include")
            .description("Detects HTTP URL in include parameter")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(file|include|require|page|path|doc|template|folder)=https?://")
            .base_score(10)
            .cwe(98)
            .tags(&["rfi", "remote"])
            .build()?,
        RuleBuilder::new(930131, "RFI: FTP include")
            .description("Detects FTP URL in include parameter")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(file|include|require|page)=ftp://")
            .base_score(10)
            .cwe(98)
            .tags(&["rfi", "remote"])
            .build()?,
        // Log poisoning
        RuleBuilder::new(930140, "LFI: Log file access")
            .description("Detects log file access for poisoning")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r"(?i)/(var/log|apache|nginx|httpd)/.+\.log")
            .base_score(7)
            .cwe(22)
            .tags(&["lfi", "log-poisoning"])
            .build()?,
        // Paranoia Level 3 - Evasion techniques
        RuleBuilder::new(930150, "Path Traversal: Unicode encoding")
            .description("Detects Unicode-encoded path traversal (overlong)")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(%u002e|%u2215|%u2216|%uff0e|%uff0f)")
            .base_score(5)
            .cwe(22)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930151, "Path Traversal: Mixed slash encoding")
            .description("Detects mixed forward/backslash encoding")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(\.\.%5c|%5c\.\.|\.\./\\|\\\.\.)")
            .base_score(5)
            .cwe(22)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930152, "Path Traversal: Triple encoding")
            .description("Detects triple URL-encoded path components")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(%25252e|%25252f|%25255c)")
            .base_score(5)
            .cwe(22)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930153, "Path Traversal: Dot padding")
            .description("Detects padded dot sequences")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"\.\.\.\./")
            .base_score(4)
            .cwe(22)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930154, "Path Traversal: Encoded null in path")
            .description("Detects encoded null bytes in path context")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(%00|%2500).*\.(php|asp|jsp|txt|log)")
            .base_score(5)
            .cwe(626)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930155, "Path Traversal: Tomcat %c0%ae bypass")
            .description("Detects Tomcat-specific UTF-8 bypass")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)%c0(%ae|%2e|%25ae)")
            .base_score(5)
            .cwe(22)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930156, "Path Traversal: Path normalization bypass")
            .description("Detects path with mixed ./ and ../ sequences")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"\./\.\./|\.\\\.\.\\")
            .base_score(4)
            .cwe(22)
            .tags(&["traversal", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930157, "Path Traversal: PHP wrapper variations")
            .description("Detects PHP wrapper variations")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(pHp|PhP)://")
            .base_score(5)
            .cwe(98)
            .tags(&["lfi", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930158, "Path Traversal: Encoded scheme")
            .description("Detects URL-encoded file:// scheme")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(%66%69%6c%65|%46%49%4c%45)://")
            .base_score(5)
            .cwe(22)
            .tags(&["lfi", "traversal-evasion", "pl3"])
            .build()?,
        RuleBuilder::new(930159, "Path Traversal: Java file access")
            .description("Detects Java-specific file access patterns")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(WEB-INF|META-INF|classes)/")
            .base_score(5)
            .cwe(22)
            .tags(&["traversal", "java", "pl3"])
            .build()?,
        // Paranoia Level 4 - Maximum sensitivity
        RuleBuilder::new(930170, "Path Traversal: Any double dot")
            .description("Detects any double dot sequence")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"\.\.")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930171, "Path Traversal: Path separator")
            .description("Detects any backslash in path")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"\\")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930172, "Path Traversal: Executable extension")
            .description("Detects executable file extensions in path")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)\.(php|asp|aspx|jsp|cgi|pl|py|rb|sh|exe|bat|cmd)\b")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930173, "Path Traversal: Config file extension")
            .description("Detects config file extensions")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)\.(conf|config|ini|xml|yaml|yml|json|env)\b")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930174, "Path Traversal: Absolute Unix path")
            .description("Detects any absolute Unix path")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"^/[a-zA-Z]")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930175, "Path Traversal: Drive letter")
            .description("Detects Windows drive letter pattern")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)[a-z]:")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930176, "Path Traversal: Hidden files")
            .description("Detects hidden file patterns (dotfiles)")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"/\.[a-zA-Z]")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930177, "Path Traversal: Percent encoding")
            .description("Detects any percent-encoded path character")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)(%2e|%2f|%5c)")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930178, "Path Traversal: URL scheme")
            .description("Detects any URL scheme in path-like context")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"[a-zA-Z]+://")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
        RuleBuilder::new(930179, "Path Traversal: Directory keywords")
            .description("Detects common sensitive directory names")
            .attack_type(AttackType::PathTraversal)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)/(etc|var|usr|home|root|tmp|proc|sys|dev|boot|opt)/")
            .base_score(2)
            .cwe(22)
            .tags(&["traversal", "traversal-generic", "pl4"])
            .build()?,
    ];

    Ok(all_rules
        .into_iter()
        .filter(|r| r.paranoia_level <= paranoia_level)
        .collect())
}
