//! Server-Side Template Injection (SSTI) Rules

use crate::rules::{AttackType, Confidence, Rule, RuleBuilder, Severity};
use anyhow::Result;

pub fn rules(paranoia_level: u8) -> Result<Vec<Rule>> {
    let all_rules = vec![
        // Generic SSTI
        RuleBuilder::new(935100, "SSTI: Template expression {{")
            .description("Detects generic template expression syntax")
            .attack_type(AttackType::Ssti)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(1)
            .pattern(r"\{\{.*\}\}")
            .base_score(7)
            .cwe(1336)
            .tags(&["ssti", "template"])
            .build()?,

        RuleBuilder::new(935101, "SSTI: Template expression ${")
            .description("Detects ${} template expression syntax")
            .attack_type(AttackType::Ssti)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(1)
            .pattern(r"\$\{.*\}")
            .base_score(7)
            .cwe(1336)
            .tags(&["ssti", "template"])
            .build()?,

        RuleBuilder::new(935102, "SSTI: Template expression <%")
            .description("Detects <% %> template expression syntax")
            .attack_type(AttackType::Ssti)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(1)
            .pattern(r"<%.*%>")
            .base_score(7)
            .cwe(1336)
            .tags(&["ssti", "template"])
            .build()?,

        // Jinja2 / Python
        RuleBuilder::new(935110, "SSTI: Jinja2 config access")
            .description("Detects Jinja2 config attribute access")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)\{\{\s*config\s*\}\}|\{\{\s*request\.")
            .base_score(9)
            .cwe(1336)
            .tags(&["ssti", "jinja2", "python"])
            .build()?,

        RuleBuilder::new(935111, "SSTI: Jinja2 class access")
            .description("Detects Jinja2 __class__ attribute access")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)__class__|__mro__|__subclasses__|__globals__|__builtins__")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "jinja2", "python", "rce"])
            .build()?,

        RuleBuilder::new(935112, "SSTI: Jinja2 popen/system")
            .description("Detects Jinja2 command execution")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(popen|system|subprocess|os\.)")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "jinja2", "python", "rce"])
            .build()?,

        // Twig (PHP)
        RuleBuilder::new(935120, "SSTI: Twig filter")
            .description("Detects Twig filter syntax")
            .attack_type(AttackType::Ssti)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r"\{\{\s*[^}]+\|")
            .base_score(6)
            .cwe(1336)
            .tags(&["ssti", "twig", "php"])
            .build()?,

        RuleBuilder::new(935121, "SSTI: Twig _self access")
            .description("Detects Twig _self attribute access")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)_self\.env\.registerUndefinedFilterCallback")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "twig", "php", "rce"])
            .build()?,

        // Freemarker (Java)
        RuleBuilder::new(935130, "SSTI: Freemarker built-ins")
            .description("Detects Freemarker built-in functions")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)\?\s*(new|api|exec|eval)")
            .base_score(9)
            .cwe(1336)
            .tags(&["ssti", "freemarker", "java"])
            .build()?,

        RuleBuilder::new(935131, "SSTI: Freemarker Execute")
            .description("Detects Freemarker Execute class")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)freemarker\.template\.utility\.Execute")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "freemarker", "java", "rce"])
            .build()?,

        // Velocity (Java)
        RuleBuilder::new(935140, "SSTI: Velocity class loading")
            .description("Detects Velocity class loading")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)\$class\.inspect|\.getClass\(\)")
            .base_score(9)
            .cwe(1336)
            .tags(&["ssti", "velocity", "java"])
            .build()?,

        RuleBuilder::new(935141, "SSTI: Velocity Runtime")
            .description("Detects Velocity Runtime access")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)\$\w+\.class\.forName|java\.lang\.Runtime")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "velocity", "java", "rce"])
            .build()?,

        // Smarty (PHP)
        RuleBuilder::new(935150, "SSTI: Smarty php tag")
            .description("Detects Smarty php tag injection")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)\{php\}|\{/php\}")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "smarty", "php", "rce"])
            .build()?,

        // Handlebars/Mustache
        RuleBuilder::new(935160, "SSTI: Handlebars helper injection")
            .description("Detects Handlebars helper injection")
            .attack_type(AttackType::Ssti)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r"\{\{#with\s+|\{\{#each\s+")
            .base_score(6)
            .cwe(1336)
            .tags(&["ssti", "handlebars", "javascript"])
            .build()?,

        // ERB (Ruby)
        RuleBuilder::new(935170, "SSTI: ERB code execution")
            .description("Detects ERB code execution")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"<%=?\s*(system|exec|`|eval|IO\.)")
            .base_score(10)
            .cwe(1336)
            .tags(&["ssti", "erb", "ruby", "rce"])
            .build()?,

        // Paranoia Level 3 - Evasion techniques
        RuleBuilder::new(935180, "SSTI: Unicode brackets")
            .description("Detects Unicode variant curly brackets")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(\uFF5B|\u007B\u007B|\uFE5B)")
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935181, "SSTI: String concatenation bypass")
            .description("Detects string concatenation in template context")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r#"\{\{['"][^'"]+['"]\s*\+\s*['"]"#)
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935182, "SSTI: Bracket attribute access")
            .description("Detects bracket notation attribute access")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r#"\['__(class|mro|globals|subclasses)__'\]"#)
            .base_score(6)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935183, "SSTI: getattr/attr function")
            .description("Detects getattr/attr for attribute access bypass")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(getattr|attr)\s*\(")
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935184, "SSTI: Encoded class attribute")
            .description("Detects URL-encoded class attributes")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(%5f%5f|%5F%5F)(class|mro|globals)")
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935185, "SSTI: Lipsum/cycler exploit")
            .description("Detects Jinja2 lipsum/cycler for RCE")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)(lipsum|cycler|joiner|namespace)\s*\.")
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "jinja2", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935186, "SSTI: Request object abuse")
            .description("Detects request object for filter bypass")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)request\s*\.\s*(application|args|cookies|data|environ)")
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "jinja2", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935187, "SSTI: Hex/octal string bypass")
            .description("Detects hex/octal strings in template")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r#"\{\{[^}]*(\\x[0-9a-f]{2}|\\[0-7]{3})"#)
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935188, "SSTI: Filter chain")
            .description("Detects multiple filters for bypass")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"\{\{[^}]+\|[^}]+\|[^}]+\}\}")
            .base_score(4)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        RuleBuilder::new(935189, "SSTI: Set/import statements")
            .description("Detects template set/import for bypass")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)\{%\s*(set|import|from|include)\s+")
            .base_score(5)
            .cwe(1336)
            .tags(&["ssti", "ssti-evasion", "pl3"])
            .build()?,

        // Paranoia Level 4 - Maximum sensitivity
        RuleBuilder::new(935190, "SSTI: Any double brace")
            .description("Detects any {{ or }} pattern")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"\{\{|\}\}")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935191, "SSTI: Any angle percent")
            .description("Detects any <% or %> pattern")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"<%|%>")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935192, "SSTI: Dollar brace")
            .description("Detects any ${ pattern")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"\$\{")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935193, "SSTI: Dunder pattern")
            .description("Detects any double underscore pattern")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"__[a-zA-Z]+__")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935194, "SSTI: Dot bracket access")
            .description("Detects attribute access patterns")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r#"\[['"][a-zA-Z_]+['"]\]"#)
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935195, "SSTI: Pipe filter")
            .description("Detects any pipe character in brace context")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"\{\{[^}]*\|")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935196, "SSTI: Hash/block syntax")
            .description("Detects Handlebars block syntax")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"\{\{#")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935197, "SSTI: Class-like words")
            .description("Detects class/object related words")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)\b(class|mro|subclasses|globals|builtins|init)\b")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935198, "SSTI: Template keywords")
            .description("Detects common template keywords")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)\b(config|request|self|env|template)\b")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,

        RuleBuilder::new(935199, "SSTI: Runtime/exec words")
            .description("Detects execution-related words")
            .attack_type(AttackType::Ssti)
            .severity(Severity::Low)
            .confidence(Confidence::Low)
            .paranoia(4)
            .pattern(r"(?i)\b(runtime|popen|system|exec|eval|import)\b")
            .base_score(2)
            .cwe(1336)
            .tags(&["ssti", "ssti-generic", "pl4"])
            .build()?,
    ];

    Ok(all_rules
        .into_iter()
        .filter(|r| r.paranoia_level <= paranoia_level)
        .collect())
}
