//! NoSQL Injection Rules (MongoDB, Redis, etc.)

use crate::rules::{AttackType, Confidence, Rule, RuleBuilder, Severity};
use anyhow::Result;

pub fn rules() -> Result<Vec<Rule>> {
    Ok(vec![
        // MongoDB injection
        RuleBuilder::new(942200, "NoSQL Injection: MongoDB operator")
            .description("Detects MongoDB query operators in input")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r#"(?i)(\$where|\$gt|\$lt|\$ne|\$eq|\$regex|\$exists|\$or|\$and|\$in|\$nin)"#)
            .base_score(9)
            .cwe(943) // NoSQL Injection
            .tags(&["nosql", "mongodb"])
            .build()?,
        RuleBuilder::new(942201, "NoSQL Injection: MongoDB $where JS")
            .description("Detects MongoDB $where with JavaScript execution")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r#"(?i)\$where\s*:\s*['\"]?function\s*\("#)
            .base_score(10)
            .cwe(943)
            .tags(&["nosql", "mongodb", "rce"])
            .build()?,
        RuleBuilder::new(942202, "NoSQL Injection: MongoDB mapReduce")
            .description("Detects MongoDB mapReduce injection")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(mapReduce|map_reduce)\s*\(")
            .base_score(10)
            .cwe(943)
            .tags(&["nosql", "mongodb", "rce"])
            .build()?,
        RuleBuilder::new(942203, "NoSQL Injection: MongoDB $regex DoS")
            .description("Detects potential ReDoS via $regex")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r#"(?i)\$regex\s*:\s*['\"].*(\*\+|\+\*|\{\d+,\})"#)
            .base_score(7)
            .cwe(943)
            .tags(&["nosql", "mongodb", "dos"])
            .build()?,
        RuleBuilder::new(942204, "NoSQL Injection: JSON operator injection")
            .description("Detects JSON-based operator injection patterns")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r#"\{\s*['\"]?\$[a-z]+['\"]?\s*:"#)
            .base_score(7)
            .cwe(943)
            .tags(&["nosql", "json"])
            .build()?,
        // Redis injection
        RuleBuilder::new(942210, "NoSQL Injection: Redis command")
            .description("Detects Redis command injection")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(
                r"(?i)\b(EVAL|EVALSHA|CONFIG|FLUSHALL|FLUSHDB|DEBUG|SHUTDOWN|SLAVEOF|REPLICAOF)\b",
            )
            .base_score(10)
            .cwe(943)
            .tags(&["nosql", "redis"])
            .build()?,
        RuleBuilder::new(942211, "NoSQL Injection: Redis Lua script")
            .description("Detects Redis Lua script injection")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r"(?i)(redis\.call|redis\.pcall)\s*\(")
            .base_score(10)
            .cwe(943)
            .tags(&["nosql", "redis", "lua"])
            .build()?,
        // CouchDB
        RuleBuilder::new(942220, "NoSQL Injection: CouchDB view")
            .description("Detects CouchDB view injection")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r"(?i)_design/.*/_view/")
            .base_score(7)
            .cwe(943)
            .tags(&["nosql", "couchdb"])
            .build()?,
        // Cassandra
        RuleBuilder::new(942230, "NoSQL Injection: Cassandra CQL")
            .description("Detects Cassandra CQL injection patterns")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::High)
            .confidence(Confidence::Medium)
            .paranoia(2)
            .pattern(r"(?i)\b(ALLOW\s+FILTERING|TOKEN\s*\(|USING\s+TTL)\b")
            .base_score(6)
            .cwe(943)
            .tags(&["nosql", "cassandra"])
            .build()?,
        // Elasticsearch
        RuleBuilder::new(942240, "NoSQL Injection: Elasticsearch script")
            .description("Detects Elasticsearch script injection")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Critical)
            .confidence(Confidence::High)
            .paranoia(1)
            .pattern(r#"(?i)("script"\s*:\s*\{|_scripts/|painless|groovy)"#)
            .base_score(9)
            .cwe(943)
            .tags(&["nosql", "elasticsearch", "rce"])
            .build()?,
        RuleBuilder::new(942241, "NoSQL Injection: Elasticsearch _search")
            .description("Detects Elasticsearch search API abuse")
            .attack_type(AttackType::SqlInjection)
            .severity(Severity::Medium)
            .confidence(Confidence::Low)
            .paranoia(3)
            .pattern(r"(?i)/_search\?")
            .base_score(4)
            .cwe(943)
            .tags(&["nosql", "elasticsearch"])
            .build()?,
    ])
}
